export const PHOTO_RFID = 'PHOTO_RFID';
export const PHOTO_INPUT = 'PHOTO_INPUT';
export const PHOTO_BEFORE_LOAD_START = 'PHOTO_BEFORE_LOAD_START';
export const PHOTO_BEFORE_LOAD_END = 'PHOTO_BEFORE_LOAD_END';
export const PHOTO_AFTER_LOAD_START = 'PHOTO_AFTER_LOAD_START';
export const PHOTO_AFTER_LOAD_END = 'PHOTO_AFTER_LOAD_END';
export const PHOTO_DELETE = 'PHOTO_DELETE';
export const PHOTO_RESET = 'PHOTO_RESET';